version: '2'
services:
  netsuivi201918547-app:
    image: netsuivi201918547
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://netsuivi201918547-postgresql:5432/Netsuivi201918547
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  netsuivi201918547-postgresql:
    extends:
      file: postgresql.yml
      service: netsuivi201918547-postgresql
